services:

  backend:
    build: ./backend
    container_name: backend_descobrindo
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: always

  frontend:
    build: ./frontend_web/descobrindo-maceio
    container_name: frontend_descobrindo
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend